# -*- coding: utf-8 -*-
GUIDES_1 = {
"buying-property-in-palghar": {
  "title": "Buying Property in Palghar: A 2026 Buyer's Guide",
  "meta": "What a flat or plot in Palghar actually involves in 2026 — localities, MahaRERA checks, carpet-area maths, infrastructure timelines and the documents to ask for. Written by a Palghar firm building here since 1992.",
  "eyebrow": "Buyer's Guide",
  "updated": "2026-09-02",
  "answer": "Palghar is the district headquarters of Palghar district, Maharashtra, roughly 110 km north of Mumbai on the Western Railway line. For buyers in 2026 the practical decision comes down to four things: which side of the station you buy on (Palghar West or Palghar East), whether the project carries a live MahaRERA registration, whether you are buying carpet area or being quoted saleable area, and how much of the price you are paying for infrastructure that has not been commissioned yet.",
  "sections": [
    {"h2": "Where is Palghar and why are people buying here?",
     "p": ["Palghar town sits on the Western Railway suburban and mainline corridor. It became a district headquarters in 2014, when Palghar district was carved out of Thane district. That change is what turned it from a station town into an administrative centre with its own collectorate, courts and district offices.",
           "The current buying interest is driven by three state and central infrastructure programmes that physically pass through or terminate in the district: Vadhavan Port at Dahanu, the Mumbai-Ahmedabad high-speed rail corridor (which has a station planned at Boisar and tunnelling underway in Palghar), and the road and expressway upgrades feeding both. Maharashtra has publicly grouped these under a 'Mumbai 4.0' growth narrative for the northern MMR.",
           "The honest caveat: these are multi-year programmes. Tunnel breakthroughs and port foundation work make news, but commissioning dates move. Buy on what Palghar is today - a district headquarters with a working railway station, schools, hospitals and a 30-minute drive to the coast - and treat the corridor projects as upside, not as the reason for the price."]},
    {"h2": "Palghar West or Palghar East - which side should you buy on?",
     "p": ["Both sides are within a few minutes of Palghar railway station, and both are actively developed. The difference is character rather than quality.",
           "Palghar West holds the older town core, the market, the collectorate side, most of the established schools and hospitals, and the Devisha Road and Vajali Pada belt where much of the recent apartment stock sits. It is denser and better serviced.",
           "Palghar East - Vevoor, Station Road and the belt running toward Boisar - has more land available, more new launches, and generally lower per-square-foot pricing. It is where plotted development and newer apartment complexes are concentrated."],
     "table": {"head": ["", "Palghar West", "Palghar East"],
               "rows": [["Character", "Established town core, market, civic offices", "Newer development, more open land"],
                        ["Typical stock", "Apartments, mixed-use, some commercial", "Apartments, plotted and NA layouts"],
                        ["Social infrastructure", "Denser - schools, hospitals, banks in place", "Growing, more dependent on the West"],
                        ["Pricing", "Generally higher per sq.ft.", "Generally lower per sq.ft."],
                        ["Best for", "End-users wanting everything walkable", "Buyers wanting space, plots, or entry pricing"]]},
     "p2": ["Neither side is a mistake. The question that matters more than the compass direction is how far the specific project is from the station and the market, measured in actual minutes, not in brochure language."]},
    {"h2": "What does a flat in Palghar cost in 2026?",
     "p": ["Pricing varies enough by locality, floor and possession stage that any single number is misleading. What is more useful is knowing the shape of the market.",
           "Palghar's residential stock is dominated by 1 BHK and 2 BHK apartments, with 3 BHK available in the larger complexes. Carpet areas in the current MahaRERA-registered stock in Palghar West run from roughly 430 sq.ft. for a 1 BHK to around 1,050 sq.ft. for a 3 BHK. Those are carpet figures taken from RERA filings, not saleable-area figures.",
           "Always ask for the price against carpet area. Under the Real Estate (Regulation and Development) Act, carpet area is the defined and disclosed measure, and it is the figure a promoter must register. A quote against 'saleable' or 'super built-up' area is not comparable to a quote against carpet area, and the gap between the two is usually 25 to 40 per cent."]},
    {"h2": "How do you check whether a Palghar project is genuine?",
     "p": ["Every registered project has a MahaRERA registration number beginning with P. You can look it up yourself, free, on the MahaRERA portal - you do not need the developer's help and you should not accept a screenshot in place of the live record.",
           "Since August 2023 MahaRERA has required promoters to display the registration number and a QR code on advertisements and marketing material, with penalties for non-compliance. If a Palghar hoarding, brochure or website carries no registration number and no QR code, that is a signal in itself.",
           "The registration page tells you the promoter's name, the sanctioned plan, the number of units, the declared completion date, and the complaints filed. Read the declared completion date against what the sales team is telling you verbally. Where they differ, the portal is the record."]},
    {"h2": "What about plots - is RERA registration needed for NA land?",
     "p": ["Yes, for plotted development. MahaRERA has held that plotted schemes and the sale of plots for non-agricultural purposes fall within the Act and require registration, and it has acted against promoters who sold NA plots without registering. Treat an unregistered plotted scheme as a risk, not a discount.",
           "For a plot purchase the document set is different from a flat. You are looking at the 7/12 extract, the non-agricultural (NA) order, the sanctioned layout, the access road status, and whether internal infrastructure has actually been laid rather than merely drawn."]},
    {"h2": "What documents should you ask for before paying anything?",
     "list": ["MahaRERA registration number, verified live on the portal - not a screenshot",
              "Title certificate from an advocate, and the chain of title",
              "Sanctioned plan and commencement certificate from the local authority",
              "For ready flats: the occupation certificate (OC)",
              "For plots: 7/12 extract, NA order, sanctioned layout, access road status",
              "The agreement for sale, with carpet area, price break-up and possession date stated in it",
              "Payment schedule tied to construction stages, and the project's designated bank account"],
     "p2": ["Pay into the project's designated account against a receipt. Cash components have no legal standing and no recourse."]},
    {"h2": "Who builds in Palghar?",
     "p": ["Palghar's development is largely local. Most active promoters are family firms that have worked in the taluka for decades, often across both apartment projects and land, rather than branches of Mumbai developers.",
           "Om Shanti N R Construction is one of them - a partnership firm registered in 2005, with partners active in Palghar real estate since 1992 and thirteen completed residential and commercial projects in the town, the earliest of which received its occupation certificate in 1996. It is currently the land partner on three MahaRERA-registered projects and is developing a plotted layout at Tembhode.",
           "When you shortlist a builder in a market like this, the useful question is not how large they are but how many of their earlier projects in the same town have received occupation certificates, and whether you can go and look at those buildings today."]}
  ],
  "faq": [
    ["Is Palghar a good place to buy property in 2026?", "Palghar works for buyers who want an owned home or plot near Mumbai at entry pricing, in a town that is already a district headquarters with functioning civic infrastructure. It is less suited to buyers who need short-term price appreciation, because the large infrastructure projects driving the narrative - Vadhavan Port and the high-speed rail corridor - are multi-year programmes with moving timelines."],
    ["How far is Palghar from Mumbai?", "Palghar is roughly 110 km north of Mumbai on the Western Railway line, connected by suburban and mainline services from Churchgate, Dadar and Borivali, and by road via NH-48 and the coastal routes."],
    ["What is the difference between carpet area and saleable area?", "Carpet area is the usable floor area within the walls of the flat and is the measure defined and disclosed under RERA. Saleable or super built-up area adds a share of common areas and is typically 25 to 40 per cent larger. Always compare prices against carpet area."],
    ["Do I need MahaRERA registration for a plot in Palghar?", "For plotted development and the sale of NA plots, yes. MahaRERA has held that such schemes require registration and has penalised promoters who sold plots without registering."],
    ["What is the minimum documentation before booking a flat in Palghar?", "The live MahaRERA registration record, the title certificate and chain of title, the sanctioned plan and commencement certificate, the occupation certificate if the building is ready, and an agreement for sale stating carpet area, price break-up and possession date."]
  ],
  "sources": [["MahaRERA project search", "https://maharera.maharashtra.gov.in/projects-search-result"],
              ["MahaRERA: RERA registration required for plotted development", "https://www.constructionworld.in/latest-construction-news/real-estate-news/-plots-for-non-farm-purpose-only-after-rera-registration--maharera-/29161"],
              ["Palghar district", "https://en.wikipedia.org/wiki/Palghar"],
              ["Bullet train tunnel breakthrough in Palghar (Feb 2026)", "https://www.newsonair.gov.in/second-mountain-tunnel-breakthrough-achieved-in-mumbai-ahmedabad-bullet-train-project-in-palghar/"]]
}
}
